# ML Models

# Imports

#### Standard library imports

In [1]:
import sys
import os
sys.path.append("../..")

#### Third party imports

In [82]:
import pandas as pd
import pickle
import numpy as np
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn import metrics
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import roc_auc_score
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

#### Local application imports

In [3]:
%load_ext autoreload
%autoreload 2

from pkg_dir.config import *
from pkg_dir.src.utils import *
from pkg_dir.src.functions import *
from pkg_dir.src.parameters import *

# Pickle Extraction

In [3]:
path = '../../pkg_dir/data/pickles'
name = 'dataset_v1.pkl'

## Reading extract object saved as pickle locally
pkl_obj = path + "/" + name

with open(pkl_obj, 'rb') as obj_content:
    df = pickle.load(obj_content)

In [4]:
df

appointment_id  appointment_weekday   appointment_start  \
2       2021923564                         5 2022-01-22 12:30:00   
3       2021853399                         0 2022-01-24 12:00:00   
4       2021845947                         0 2022-01-31 13:00:00   
5       2021924951                         1 2022-01-25 13:30:00   
6       2021889374                         5 2022-01-22 08:00:00   
...                 ...                  ...                 ...   
544083  2022136584                         3 2022-12-29 10:00:00   
544084  2022141229                         2 2022-11-30 08:30:00   
544085  2022506277                         5 2022-06-25 10:00:00   
544086  2023228381                         3 2023-01-05 08:30:00   
544087  2023000312555                      1 2023-01-31 13:30:00   

        appointment_dur_min recurring_patient  creation_to_start_hrs  \
2                      30.0             first                  20.52   
3                      30.0             first                  52.19   
4                      30.0             first                 221.78   
5                      30.0             first                  78.35   
6                      30.0             first                  24.22   
...                     ...               ...                    ...   
544083                 30.0         recurrent                2181.63   
544084                 30.0         recurrent                  14.12   
544085                 30.0             first                  25.08   
544086                 30.0         recurrent                  39.87   
544087                 30.0               NaN               -8345.70   

        confirm_request_msg  patient_confirm  confirm_to_start_hrs  \
2                         0                0                   NaN   
3                         0                0                   NaN   
4                         0                0                   NaN   
5                         0                0                   NaN   
6                         0                1                 21.75   
...                     ...              ...                   ...   
544083                    1                1                 49.28   
544084                    0                1                 14.05   
544085                    0                1                 19.02   
544086                    0                1                 15.32   
544087                    0                0                   NaN   

                 clinic appointment_source appointment_date_update  \
2       MARINA NACIONAL              phone               no_update   
3       MARINA NACIONAL              phone               no_update   
4               TLALPAN              phone               no_update   
5              BASILICA              phone               no_update   
6              BASILICA              phone               no_update   
...                 ...                ...                     ...   
544083            COAPA              phone               no_update   
544084            COAPA              phone               no_update   
544085            COAPA              phone               no_update   
544086            COAPA              phone               no_update   
544087  MARINA NACIONAL             online               no_update   

        patient_age patient_sex                                  doctor  \
2              32.0           F     DR. ORLANDO JOSE HERNANDEZ MARTINEZ   
3              32.0           F  DRA JUANA GUADALUPE CABALLERO MARTINEZ   
4              32.0           F                   Mariana  Sarao Pineda   
5              32.0           F        DRA ANA MARIA ESCOBEDO HERNANDEZ   
6              40.0           F        DRA MONICA MARCELA MACIAS ORTEGA   
...             ...         ...                                     ...   
544083         60.0           M       DRA LAURA FABIOLA PORTILLO GARCIA   
544084         33.0           M        DR. MI

In [5]:
df.columns
#relevant columns: appointment_weekday, appointment_dur_min, recurring_patient, creation_to_start_hrs, confirm_request_msg, 
#confirm_to_start_hrs, clinic, appointment_source, appointment_date_update, rounded_start_times

#missing data: recurring_patient, creation_to_start_hrs, confirm_to_start_hrs, patient_age, patient_sex 

Index(['appointment_id', 'appointment_weekday', 'appointment_start',
       'appointment_dur_min', 'recurring_patient', 'creation_to_start_hrs',
       'confirm_request_msg', 'patient_confirm', 'confirm_to_start_hrs',
       'clinic', 'appointment_source', 'appointment_date_update',
       'patient_age', 'patient_sex', 'doctor', 'medical_specialty',
       'appointment_status_simplified'],
      dtype='object')

In [6]:
df['appointment_weekday'].isna().mean()

0.0

In [7]:
rounded_times = pd.to_datetime(df['appointment_start']).dt.round('30min')
df['rounded_start_times'] = rounded_times.dt.strftime('%H:%M:%S')

In [8]:
df['confirm_to_start_hrs'].mean() #replace na

31.54249449537882

In [9]:
df.isna().mean()

appointment_id                   0.000000
appointment_weekday              0.000000
appointment_start                0.000000
appointment_dur_min              0.000000
recurring_patient                0.002816
creation_to_start_hrs            0.019948
confirm_request_msg              0.000000
patient_confirm                  0.000000
confirm_to_start_hrs             0.233176
clinic                           0.000000
appointment_source               0.000000
appointment_date_update          0.000000
patient_age                      0.003889
patient_sex                      0.015100
doctor                           0.000000
medical_specialty                0.000000
appointment_status_simplified    0.000000
rounded_start_times              0.000000
dtype: float64

In [10]:
df['medical_specialty'].replace({'Ultrasonido': 'ULTRASONIDO'}, inplace = True)

In [11]:
df['confirm_to_start_hrs'].fillna(df['confirm_to_start_hrs'].mean(), inplace = True)

In [12]:
df.dropna(subset= ['recurring_patient', 'creation_to_start_hrs', 'patient_age', 'patient_sex'], inplace = True)

In [13]:
df.drop(columns = ['appointment_id', 'appointment_start'], inplace = True)

In [14]:
X = df.drop(columns = ['appointment_status_simplified'])
y = df['appointment_status_simplified']

In [19]:
X

appointment_weekday  appointment_dur_min recurring_patient  \
2                         5                 30.0             first   
3                         0                 30.0             first   
4                         0                 30.0             first   
5                         1                 30.0             first   
6                         5                 30.0             first   
...                     ...                  ...               ...   
544082                    3                 30.0         recurrent   
544083                    3                 30.0         recurrent   
544084                    2                 30.0         recurrent   
544085                    5                 30.0             first   
544086                    3                 30.0         recurrent   

        creation_to_start_hrs  confirm_request_msg  patient_confirm  \
2                       20.52                    0                0   
3                       52.19                    0                0   
4                      221.78                    0                0   
5                       78.35                    0                0   
6                       24.22                    0                1   
...                       ...                  ...              ...   
544082                1510.57                    0                1   
544083                2181.63                    1                1   
544084                  14.12                    0                1   
544085                  25.08                    0                1   
544086                  39.87                    0                1   

        confirm_to_start_hrs           clinic appointment_source  \
2                  31.542494  MARINA NACIONAL              phone   
3                  31.542494  MARINA NACIONAL              phone   
4                  31.542494          TLALPAN              phone   
5                  31.542494         BASILICA              phone   
6                  21.750000         BASILICA              phone   
...                      ...              ...                ...   
544082             26.570000            COAPA              phone   
544083             49.280000            COAPA              phone   
544084             14.050000            COAPA              phone   
544085             19.020000            COAPA              phone   
544086             15.320000            COAPA              phone   

       appointment_date_update  patient_age patient_sex  \
2                    no_update         32.0           F   
3                    no_update         32.0           F   
4                    no_update         32.0           F   
5                    no_update         32.0           F   
6                    no_update         40.0           F   
...                        ...          ...         ...   
544082               no_update         60.0           M   
544083               no_update         60.0           M   
544084               no_update         33.0           M   
544085               no_update         33.0           M   
544086               no_update         33.0           M   

                                        doctor     medical_specialty  \
2          DR. ORLANDO JOSE HERNANDEZ MARTINEZ              UROLOGIA   
3       DRA JUANA GUADALUPE CABALLERO MARTINEZ           GINECOLOGIA   
4                        Mariana  Sarao Pineda          DERMATOLOGIA   
5             DRA ANA MARIA ESCOBEDO HERNANDEZ          DERMATOLOGIA   
6             DRA MONICA MARCELA MACIAS ORTEGA        ENDOCRINOLOGIA   
...                                        ...                   ...   
544082       DRA LAURA FABIOLA PORTILLO GARCIA            NEFROLOGIA   
544083       DRA LAURA FABIOLA PORTILLO GARCIA            NEFROLOGIA   
544084        DR. MIGUEL ANGEL MONTERO MARQUEZ  OTORRINOLARINGOLOGIA   
544085   DRA SANDRA XOCHIQUETZAL  CRUZ ORDOÑEZ              UROLOGIA

In [15]:
X_train, X_test, y_train_old, y_test_old = train_test_split(X, y, test_size=0.25, random_state=42)

In [16]:
le = LabelEncoder()
y_train = le.fit_transform(y_train_old)
y_test = le.fit_transform(y_test_old)

In [19]:
y_train, y_test

(array([1, 2, 1, ..., 2, 1, 1]), array([1, 1, 1, ..., 1, 2, 0]))

In [20]:
most_common_label = np.argmax(np.bincount(y_train))
baseline_1_acc = (y_test == most_common_label).mean()
baseline_1_acc

0.6401005534756762

In [21]:
encoder = OneHotEncoder(handle_unknown="ignore")
encoder.fit(X_train)
X_train = encoder.transform(X_train)
X_test = encoder.transform(X_test)

In [22]:
model = LogisticRegression(multi_class='multinomial', solver='lbfgs')

In [23]:
model.fit(X_train, y_train)

/usr/local/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(multi_class='multinomial')

In [24]:
y_pred = model.predict(X_test)
y_pred_proba = model.predict_proba(X_test)

In [25]:
model_acc = accuracy_score(y_test, y_pred)

In [26]:
model_acc

0.7915781069621414

In [27]:
coefficients = model.coef_[0]

In [28]:
for feature, coef in zip(X.columns, coefficients):
    print(f"{feature}: {coef}")

appointment_weekday: -0.08053486387505376
appointment_dur_min: 0.060244979370688616
recurring_patient: 0.04577819009295222
creation_to_start_hrs: 0.08550159874942155
confirm_request_msg: 0.09098373318722333
patient_confirm: 0.05308090131474075
confirm_to_start_hrs: -0.3913676469438612
clinic: 0.004925207343934351
appointment_source: -0.11894096685114629
appointment_date_update: -0.6644510098856173
patient_age: 1.078243512136026
patient_sex: -0.2871608489375163
doctor: 0.26998263472340134
medical_specialty: 0.3464975853450315
rounded_start_times: 0.18992254670121425


In [29]:
most_significant_features = [feature for feature, coef in zip(X.columns, coefficients) if abs(coef) > 0.1]
print("Most significant features:", most_significant_features)

Most significant features: ['confirm_to_start_hrs', 'appointment_source', 'appointment_date_update', 'patient_age', 'patient_sex', 'doctor', 'medical_specialty', 'rounded_start_times']


In [33]:
roc_auc_micro = roc_auc_score(y_test, y_pred_proba, multi_class='ovr', average='micro')
print(f'Logistic Regression Test AUC: {roc_auc_micro:.4f}')
cm_logistic = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm_logistic)
print ("\nAccuracy:", accuracy_score(y_test, y_pred))

Logistic Regression Test AUC: 0.8820
Confusion Matrix : 
 [[15524  4370   294]
 [ 1457 57494   378]
 [ 2282 10537   351]]

Accuracy: 0.7915781069621414


In [37]:
true_positives = np.diag(cm_logistic)
false_positives = np.sum(cm_logistic, axis=0) - true_positives
false_negatives = np.sum(cm_logistic, axis=1) - true_positives
true_negatives = np.sum(cm_logistic) - (true_positives + false_positives + false_negatives)


# Calculate False Positive Rate (FPR), False Negative Rate (FNR), and True Positive Rate (TPR)
fpr = false_positives / (false_positives + true_negatives)
fnr = false_negatives / (false_negatives + true_positives)
tpr = true_positives / (true_positives + false_negatives)

#0 cancel, #1 completed, #2 no_show
print("False Positive Rate (FPR):", fpr)
print("False Negative Rate (FNR):", fnr)
print("True Positive Rate (TPR):", tpr)


False Positive Rate (FPR): [0.05157313 0.44687931 0.00845102]
False Negative Rate (FNR): [0.23102833 0.03092923 0.97334852]
True Positive Rate (TPR): [0.76897167 0.96907077 0.02665148]


In [35]:
dtc = DecisionTreeClassifier(random_state = 10)
dtc = dtc.fit(X_train, y_train)

In [174]:
y_pred_dtc = dtc.predict(X_test)
cm_dtc = confusion_matrix(y_test, y_pred_dtc)
print ("Confusion Matrix : \n", cm_dtc)
print ("\nAccuracy:", accuracy_score(y_test, y_pred_dtc))

Confusion Matrix : 
 [[14123  3815  2250]
 [ 3803 47157  8369]
 [ 2188  8293  2689]]

Accuracy: 0.690161511323055


In [176]:
rf = RandomForestClassifier(max_depth=5)
rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=5)

In [177]:
y_pred_rf = rf.predict(X_test)
cm_rf = confusion_matrix(y_test, y_pred_rf)
print ("Confusion Matrix: \n", cm_rf)
print ("\nAccuracy:", accuracy_score(y_test, y_pred_rf))

Confusion Matrix: 
 [[ 4213 15975     0]
 [  121 59208     0]
 [ 1026 12144     0]]

Accuracy: 0.684249139577287


In [28]:
lda = LinearDiscriminantAnalysis()
lda.fit(X_train,y_train)

: 

In [179]:
y_pred_lda = lda.predict(X_test)
lda_acc = accuracy_score(y_test, y_pred_lda)
print(f'LDA Test Accuracy: {lda_acc:.4f}')
cm_lda = confusion_matrix(y_test, y_pred_lda)
print ("Confusion Matrix: \n", cm_lda)

LDA Test Accuracy: 0.7927
Confusion Matrix: 
 [[15786  4352    50]
 [ 1697 57606    26]
 [ 2531 10556    83]]


In [22]:
path = '../../pkg_dir/data/pickles'
name = 'dataset_v2.pkl'

## Reading extract object saved as pickle locally
pkl_obj = path + "/" + name

with open(pkl_obj, 'rb') as obj_content:
    df2 = pickle.load(obj_content)

In [23]:
path = '../../pkg_dir/data/pickles'
name = 'dataset_v3.pkl'

## Reading extract object saved as pickle locally
pkl_obj = path + "/" + name

with open(pkl_obj, 'rb') as obj_content:
    df3 = pickle.load(obj_content)

In [43]:
path = '../../pkg_dir/data/pickles'
name = 'dataset_v4.pkl'

## Reading extract object saved as pickle locally
pkl_obj = path + "/" + name

with open(pkl_obj, 'rb') as obj_content:
    df4 = pickle.load(obj_content)

In [44]:
df4.drop(columns = ['clinic','doctor'], inplace = True)

In [55]:
rounded_times = pd.to_datetime(df4['appointment_start']).dt.round('60min')
df4['rounded_times'] = rounded_times.dt.strftime('%H:%M:%S')

In [56]:
months = [m.strftime('%B') for m in df4['appointment_start']]

In [57]:
df4['month'] = months
df4.drop(columns = ['appointment_start', 'appointment_id', 'appointment_dur_min'], inplace = True)

In [58]:
df4.dropna(inplace = True)

In [ ]:
df4.drop(columns = ['time', 'month'], inplace = True)

In [59]:
df4

appointment_weekday recurring_patient  creation_to_start_hrs  \
21                        2             first                 776.55   
23                        5             first                1415.13   
49                        4             first                 154.24   
64                        0             first                  97.30   
92                        5         recurrent                 332.75   
...                     ...               ...                    ...   
544022                    1             first                  78.32   
544045                    3             first                  19.37   
544052                    4             first                  30.73   
544058                    4             first                  26.68   
544060                    4             first                  20.48   

        confirm_request_msg  patient_confirm  confirm_to_start_hrs  \
21                        0                1                 34.18   
23                        0                1                 23.58   
49                        0                1                 33.55   
64                        0                1                 46.28   
92                        0                1                 23.68   
...                     ...              ...                   ...   
544022                    0                1                 78.27   
544045                    0                1                 19.37   
544052                    0                1                 -0.13   
544058                    0                1                 26.68   
544060                    0                1                 20.48   

       appointment_source appointment_date_update  patient_age patient_sex  \
21                  phone               no_update         18.0           F   
23                  phone               no_update         44.0           F   
49                  phone               no_update         44.0           F   
64                  phone               no_update         22.0           F   
92                  phone               no_update         21.0           M   
...                   ...                     ...          ...         ...   
544022              phone               no_update         50.0           F   
544045              phone               no_update         22.0           F   
544052              phone               no_update         32.0           F   
544058              phone               no_update         58.0           F   
544060              phone               no_update         44.0           M   

           medical_specialty appointment_status_simplified rounded_times  \
21              DERMATOLOGIA                     completed      20:00:00   
23              DERMATOLOGIA                     completed      08:00:00   
49              DERMATOLOGIA                     completed      19:00:00   
64               GINECOLOGIA                       no_show      10:00:00   
92              DERMATOLOGIA                     completed      09:00:00   
...                      ...                           ...           ...   
544022          DERMATOLOGIA                     completed      18:00:00   
544045  OTORRINOLARINGOLOGIA                     completed      08:00:00   
544052           GINECOLOGIA                     completed      16:00:00   
544058          DERMATOLOGIA                     completed      13:00:00   
544060          DERMATOLOGIA                       no_show      08:00:00   

           month  
21      February  
23       January  
49       January  
64       January  
92       January  
...          ...  
544022  December  
544045  December  
544052  December  
544058  December  
544060  December  

[48052 rows x 14 columns]

In [60]:
X = pd.get_dummies(df4.drop(columns = ['appointment_status_simplified']))
y = df4['appointment_status_simplified']

In [61]:
X_train, X_test, y_train_old, y_test_old = train_test_split(X, y, test_size=0.25, random_state=42)

In [62]:
le = LabelEncoder()
y_train = le.fit_transform(y_train_old)
y_test = le.fit_transform(y_test_old)

In [71]:
most_common_label = np.argmax(np.bincount(y_train))
baseline_1_acc = (y_test == most_common_label).mean()
baseline_1_acc

0.7718305169399817

In [101]:
logreg = LogisticRegression(multi_class='multinomial', solver='lbfgs')

In [102]:
logreg.fit(X_train, y_train)

/usr/local/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(multi_class='multinomial')

In [104]:
y_pred_log = model.predict(X_test)

In [105]:
print(classification_report(y_test, y_pred_log))

              precision    recall  f1-score   support

           0       0.51      0.03      0.06       652
           1       0.77      1.00      0.87      9272
           2       0.14      0.00      0.00      2089

    accuracy                           0.77     12013
   macro avg       0.48      0.34      0.31     12013
weighted avg       0.65      0.77      0.68     12013



In [106]:
coefficients = logreg.coef_[0]
for feature, coef in zip(X.columns, coefficients):
    print(f"{feature}: {coef}")

appointment_weekday: -0.15537605457894074
creation_to_start_hrs: -0.0002788558711754355
confirm_request_msg: 0.01148890997880348
patient_confirm: -0.1407591505287899
confirm_to_start_hrs: 0.004056874919843806
patient_age: -0.004699666557646977
recurring_patient_first: -0.1055299233730342
recurring_patient_recurrent: -0.035229227155738334
appointment_source_online: -0.0014442059018435797
appointment_source_phone: -0.13931494462695684
appointment_date_update_no_update: -0.14735034979455533
appointment_date_update_update: 0.006591199265771638
patient_sex_F: -0.07819211076855033
patient_sex_M: -0.06256703976023759
medical_specialty_DERMATOLOGIA: -0.08998786319463495
medical_specialty_GINECOLOGIA: -0.03508402784959304
medical_specialty_OTORRINOLARINGOLOGIA: -0.006972589065830168
medical_specialty_UROLOGIA: -0.008714670418740182
rounded_times_07:00:00: -0.0020495951478421365
rounded_times_08:00:00: -0.017849415824627658
rounded_times_09:00:00: -0.007172600981775316
rounded_times_10:00:00: -0

In [74]:
params = {'max_features': np.arange(1, len(X_train.columns) + 1)}
rfc = RandomForestClassifier(random_state = 88, max_depth=5)
rfc_cv = GridSearchCV(rfc, params, cv = 5, scoring = 'accuracy',verbose = False)
rfc_cv.fit(X_train, y_train)
y_pred_rfc = rfc_cv.best_estimator_.predict(X_test)

0.774827270457005

In [99]:
print(classification_report(y_test, y_pred_rfc))

              precision    recall  f1-score   support

           0       0.58      0.07      0.13       652
           1       0.78      1.00      0.87      9272
           2       0.89      0.00      0.01      2089

    accuracy                           0.77     12013
   macro avg       0.75      0.36      0.34     12013
weighted avg       0.79      0.77      0.68     12013



In [109]:
feature_importances = rfc_cv.best_estimator_.feature_importances_
# Display feature importances
for feature, importance in zip(X.columns, feature_importances):
    print(f'{feature}: {importance}')

appointment_weekday: 0.020530756097385423
creation_to_start_hrs: 0.1769076133807584
confirm_request_msg: 0.0510704793670824
patient_confirm: 0.0
confirm_to_start_hrs: 0.4920649880925885
patient_age: 0.17350866221729996
recurring_patient_first: 0.005162449016152291
recurring_patient_recurrent: 0.004471230450894838
appointment_source_online: 0.0008323740731131491
appointment_source_phone: 0.0008823664143405849
appointment_date_update_no_update: 0.0030651101115215765
appointment_date_update_update: 0.0034959291704376246
patient_sex_F: 0.002252729681802592
patient_sex_M: 0.0008685566871489292
medical_specialty_DERMATOLOGIA: 0.014451741963892374
medical_specialty_GINECOLOGIA: 0.002741358239288189
medical_specialty_OTORRINOLARINGOLOGIA: 0.001794743461238444
medical_specialty_UROLOGIA: 0.008034734788390977
rounded_times_07:00:00: 0.0020171857207059453
rounded_times_08:00:00: 0.0012703757716167215
rounded_times_09:00:00: 0.0002825403196572334
rounded_times_10:00:00: 0.0009757866121490271
round

In [75]:
gbc = GradientBoostingClassifier(n_estimators = 3300, max_leaf_nodes = 10, random_state = 88)
gbc.fit(X_train, y_train) 
y_pred_gbc = gbc.predict(X_test)

0.7619245817031549

In [97]:
print(classification_report(y_test, y_pred_gbc))

              precision    recall  f1-score   support

           0       0.48      0.12      0.19       652
           1       0.78      0.97      0.86      9272
           2       0.28      0.05      0.09      2089

    accuracy                           0.76     12013
   macro avg       0.51      0.38      0.38     12013
weighted avg       0.68      0.76      0.69     12013



In [114]:
feature_importances = gbc.feature_importances_
# Display feature importances
for feature, importance in zip(X.columns, feature_importances):
    print(f'{feature}: {importance}')

appointment_weekday: 0.03338784509483776
creation_to_start_hrs: 0.3385837317272868
confirm_request_msg: 0.0204737966000304
patient_confirm: 0.0
confirm_to_start_hrs: 0.283955203104199
patient_age: 0.10784976983883166
recurring_patient_first: 0.005242498365300948
recurring_patient_recurrent: 0.004610612480363044
appointment_source_online: 0.00112337874717397
appointment_source_phone: 0.0011444677151788193
appointment_date_update_no_update: 0.0043375309275258496
appointment_date_update_update: 0.004085086070962494
patient_sex_F: 0.0041326961653400255
patient_sex_M: 0.004080394243453123
medical_specialty_DERMATOLOGIA: 0.010897008200580824
medical_specialty_GINECOLOGIA: 0.010169562211390577
medical_specialty_OTORRINOLARINGOLOGIA: 0.008183755422039533
medical_specialty_UROLOGIA: 0.00662312074128278
rounded_times_07:00:00: 0.00323321013503676
rounded_times_08:00:00: 0.00645005422204147
rounded_times_09:00:00: 0.005019517793892648
rounded_times_10:00:00: 0.005439617033446911
rounded_times_11:

In [76]:
dtc = DecisionTreeClassifier(random_state = 10)
dtc = dtc.fit(X_train, y_train)
y_pred_dtc = dtc.predict(X_test)

0.6357279613751768

In [95]:
print(classification_report(y_test, y_pred_dtc))

              precision    recall  f1-score   support

           0       0.12      0.15      0.13       652
           1       0.79      0.77      0.78      9272
           2       0.20      0.21      0.20      2089

    accuracy                           0.64     12013
   macro avg       0.37      0.37      0.37     12013
weighted avg       0.65      0.64      0.64     12013



In [115]:
feature_importances = dtc.feature_importances_
# Display feature importances
for feature, importance in zip(X.columns, feature_importances):
    print(f'{feature}: {importance}')

appointment_weekday: 0.058431905097469
creation_to_start_hrs: 0.20013785430367784
confirm_request_msg: 0.008422619790795945
patient_confirm: 0.0
confirm_to_start_hrs: 0.2013447851830968
patient_age: 0.1432398030779084
recurring_patient_first: 0.005984059001295175
recurring_patient_recurrent: 0.004933375087491277
appointment_source_online: 0.0008841458618540233
appointment_source_phone: 0.0008541134511232579
appointment_date_update_no_update: 0.00428987393115933
appointment_date_update_update: 0.0046355354469496705
patient_sex_F: 0.014331108331245894
patient_sex_M: 0.013678479721569657
medical_specialty_DERMATOLOGIA: 0.008661647049783262
medical_specialty_GINECOLOGIA: 0.012620342795349841
medical_specialty_OTORRINOLARINGOLOGIA: 0.010695985135775677
medical_specialty_UROLOGIA: 0.009170314519615783
rounded_times_07:00:00: 0.0037412906518573996
rounded_times_08:00:00: 0.011331425917505992
rounded_times_09:00:00: 0.007954531288129571
rounded_times_10:00:00: 0.015124688549951876
rounded_time

In [77]:
lda = LinearDiscriminantAnalysis()
lda.fit(X_train,y_train)
y_pred_lda = lda.predict(X_test)

0.7723299758594856

In [94]:
print(classification_report(y_test, y_pred_lda))

              precision    recall  f1-score   support

           0       0.67      0.02      0.03       652
           1       0.77      1.00      0.87      9272
           2       0.00      0.00      0.00      2089

    accuracy                           0.77     12013
   macro avg       0.48      0.34      0.30     12013
weighted avg       0.63      0.77      0.67     12013



In [79]:
lda.coef_[0]
for feature, coef in zip(X.columns, coefficients):
    print(f"{feature}: {coef}")

appointment_weekday: -0.15537605457894074
creation_to_start_hrs: -0.0002788558711754355
confirm_request_msg: 0.01148890997880348
patient_confirm: -0.1407591505287899
confirm_to_start_hrs: 0.004056874919843806
patient_age: -0.004699666557646977
recurring_patient_first: -0.1055299233730342
recurring_patient_recurrent: -0.035229227155738334
appointment_source_online: -0.0014442059018435797
appointment_source_phone: -0.13931494462695684
appointment_date_update_no_update: -0.14735034979455533
appointment_date_update_update: 0.006591199265771638
patient_sex_F: -0.07819211076855033
patient_sex_M: -0.06256703976023759
medical_specialty_DERMATOLOGIA: -0.08998786319463495
medical_specialty_GINECOLOGIA: -0.03508402784959304
medical_specialty_OTORRINOLARINGOLOGIA: -0.006972589065830168
medical_specialty_UROLOGIA: -0.008714670418740182
rounded_times_07:00:00: -0.0020495951478421365
rounded_times_08:00:00: -0.017849415824627658
rounded_times_09:00:00: -0.007172600981775316
rounded_times_10:00:00: -0

In [92]:
knn_classifier = KNeighborsClassifier(n_neighbors=30)

# Train the classifier
knn_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = knn_classifier.predict(X_test)

# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

# Display classification report
print('Classification Report:')
print(classification_report(y_test, y_pred))

Accuracy: 0.7732456505452426
Classification Report:
              precision    recall  f1-score   support

           0       0.49      0.08      0.13       652
           1       0.78      1.00      0.87      9272
           2       0.25      0.00      0.00      2089

    accuracy                           0.77     12013
   macro avg       0.51      0.36      0.34     12013
weighted avg       0.67      0.77      0.68     12013

